services:
  postgres:
    container_name: pudl-postgres
    image: postgres:18.0-alpine3.22
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=db
    ports:
      - "3601:5432"
    restart: always
